### ISSUE TITLE
Replace Highlighter with Prism?

### ISSUE THREAD

**Issue by elazar** [tighten/jigsaw-blog-template#76]
See [this blog post](https://matthewturland.com/2017/05/20/syntax-highlighting-with-prism/). I suspect Prism may be smaller in terms of size impact on frontend builds, but it'd be worth experimenting to confirm that. I also suspect the functionality of Prism is at least equivalent, if not more robust.

**Comment by bakerkretzmar** [comment]
Interesting! I'm open to this if you want to PR it, might not get to it myself soon 😅
