### ISSUE TITLE
jigsaw-blog-template 1.2.0 is broken with jigsaw 1.3.34

### ISSUE THREAD

**Issue by elazar** [tighten/jigsaw-blog-template#79]
`jigsaw init blog` terminates with this error:

```
> npm run local
npm ERR! missing script: local

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-07T00_44_50_430Z-debug.log

There was an error running the command 'npm run local'
```

This likely stems from the `local` npm script being removed in [this change](https://github.com/tighten/jigsaw-blog-template/compare/v1.1.2...v1.2.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4).

```
vendor/tightenco/jigsaw/stubs/mix/package.json:        "dev": "npm run local",
vendor/tightenco/jigsaw/stubs/mix/package.json:        "watch": "npm run local -- --watch"
vendor/tightenco/jigsaw/src/Scaffold/DefaultInstaller.php:        'npm run local',
```

The easiest way to address this is probably to create a `local` script that invokes the same command as the `dev` script: `mix watch`.

**Comment by bakerkretzmar** [comment]
Thanks! Should be fixed in Jigsaw v1.3.35, it'll run `npm run dev` now.
