### ISSUE TITLE
deprecate @apply

### ISSUE THREAD

**Issue by bingalls** [tighten/jigsaw-blog-template#87]
Draft `@apply` has been abandoned: https://tabatkins.github.io/specs/css-apply-rule/

Open to suggestions on how to replace it in

- source/_assets/css/base.css
- source/_assets/css/mailchimp.css

Consider adopting stylelint or similar.

**Comment by bakerkretzmar** [comment]
`@apply` in the css files in this template is a [Tailwind feature](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply), not the rule from that spec.
